export {
  BASE_PINCH_ABILITY_TYPES,
  BASE_PLATE_ITEMS,
  BASE_TYPE_BOOST_ITEMS,
} from "./damage-calc-shared";
export { CORE_MECHANIC_MULTIPLIERS } from "./mechanics";
export { ALL_NATURES, NATURES_BY_ID } from "./natures";
export {
  CORE_ABILITY_SLOTS,
  CORE_ABILITY_IDS,
  CORE_END_OF_TURN_EFFECT_IDS,
  CORE_FIXED_POINT,
  CORE_GENDERS,
  CORE_GIMMICK_IDS,
  CORE_HAZARD_IDS,
  CORE_ITEM_IDS,
  CORE_MOVE_CATEGORIES,
  CORE_MOVE_IDS,
  CORE_NATURE_IDS,
  CORE_SCREEN_IDS,
  CORE_STATUS_IDS,
  CORE_TERRAIN_IDS,
  CORE_TYPE_IDS,
  CORE_VOLATILE_IDS,
  CORE_WEATHER_IDS,
} from "./reference-ids";
export { GEN6_TYPE_CHART } from "./type-chart-data";
