/**
 * Shared reference identifiers used across packages and tests.
 *
 * These remain lowercase string literals to match the repo's canonical entity ids.
 * The goal is to expose a single import surface for common domain ids/constants so
 * tests do not need to re-declare brittle file-local string bags.
 */

export const CORE_FIXED_POINT = {
  boost12: 4915,
  boost13: 5325,
  boost15: 6144,
  half: 2048,
  identity: 4096,
  gemBoost: 5325,
  resistHalf: 2048,
  spreadModifier: 3072,
  typeBoost: 4915,
} as const;

export const CORE_ABILITY_IDS = {
  blaze: "blaze",
  badDreams: "bad-dreams",
  defeatist: "defeatist",
  drizzle: "drizzle",
  drought: "drought",
  flashFire: "flash-fire",
  harvest: "harvest",
  klutz: "klutz",
  levitate: "levitate",
  intimidate: "intimidate",
  lightningRod: "lightning-rod",
  marvelScale: "marvel-scale",
  moldBreaker: "mold-breaker",
  moody: "moody",
  naturalCure: "natural-cure",
  cuteCharm: "cute-charm",
  pressure: "pressure",
  none: "none",
  pickup: "pickup",
  poisonHeal: "poison-heal",
  rainDish: "rain-dish",
  scrappy: "scrappy",
  shedSkin: "shed-skin",
  simple: "simple",
  skillLink: "skill-link",
  slowStart: "slow-start",
  solarPower: "solar-power",
  soundproof: "soundproof",
  speedBoost: "speed-boost",
  steadfast: "steadfast",
  static: "static",
  sturdy: "sturdy",
  torrent: "torrent",
  unburden: "unburden",
  wonderGuard: "wonder-guard",
} as const;

export const CORE_ITEM_IDS = {
  adamantOrb: "adamant-orb",
  airBalloon: "air-balloon",
  blackSludge: "black-sludge",
  chilanBerry: "chilan-berry",
  choiceBand: "choice-band",
  deepSeaScale: "deep-sea-scale",
  deepSeaTooth: "deep-sea-tooth",
  focusSash: "focus-sash",
  flameOrb: "flame-orb",
  griseousOrb: "griseous-orb",
  ironBall: "iron-ball",
  leftovers: "leftovers",
  lightBall: "light-ball",
  lustrousOrb: "lustrous-orb",
  normalGem: "normal-gem",
  occaBerry: "occa-berry",
  toxicOrb: "toxic-orb",
  soulDew: "soul-dew",
  thickClub: "thick-club",
  yacheBerry: "yache-berry",
} as const;

export const CORE_MOVE_IDS = {
  aerialAce: "aerial-ace",
  acrobatics: "acrobatics",
  aquaRing: "aqua-ring",
  bind: "bind",
  bounce: "bounce",
  confusion: "confusion",
  doubleEdge: "double-edge",
  energyBall: "energy-ball",
  firePledge: "fire-pledge",
  flameCharge: "flame-charge",
  flamethrower: "flamethrower",
  focusBlast: "focus-blast",
  fly: "fly",
  futureSight: "future-sight",
  grassPledge: "grass-pledge",
  growl: "growl",
  headbutt: "headbutt",
  hex: "hex",
  leechSeed: "leech-seed",
  machPunch: "mach-punch",
  gravity: "gravity",
  luckyChant: "lucky-chant",
  perishSong: "perish-song",
  quickAttack: "quick-attack",
  pursuit: "pursuit",
  round: "round",
  skyDrop: "sky-drop",
  solarBeam: "solar-beam",
  sleepTalk: "sleep-talk",
  snore: "snore",
  stealthRock: "stealth-rock",
  struggle: "struggle",
  scratch: "scratch",
  surf: "surf",
  swift: "swift",
  sketch: "sketch",
  tackle: "tackle",
  thunderbolt: "thunderbolt",
  swordsDance: "swords-dance",
  triAttack: "tri-attack",
  wish: "wish",
  waterPledge: "water-pledge",
} as const;

export const CORE_HAZARD_IDS = {
  spikes: "spikes",
  stealthRock: "stealth-rock",
  stickyWeb: "sticky-web",
  toxicSpikes: "toxic-spikes",
} as const;

export const CORE_GIMMICK_IDS = {
  mega: "mega",
} as const;

export const CORE_END_OF_TURN_EFFECT_IDS = {
  defrost: "defrost",
  disableCountdown: "disable-countdown",
  encoreCountdown: "encore-countdown",
  futureAttack: "future-attack",
  healingItems: "healing-items",
  screenCountdown: "screen-countdown",
  statBoostingItems: "stat-boosting-items",
  statusDamage: "status-damage",
  tailwindCountdown: "tailwind-countdown",
  terrainCountdown: "terrain-countdown",
  trickRoomCountdown: "trick-room-countdown",
  weatherCountdown: "weather-countdown",
  weatherDamage: "weather-damage",
  wish: "wish",
} as const;

export const CORE_TERRAIN_IDS = {
  electric: "electric",
  electricTerrain: "electric-terrain",
  grassyTerrain: "grassy-terrain",
  testSource: "test",
} as const;

export const CORE_TYPE_IDS = {
  bug: "bug",
  dark: "dark",
  dragon: "dragon",
  electric: "electric",
  fairy: "fairy",
  fighting: "fighting",
  fire: "fire",
  flying: "flying",
  ghost: "ghost",
  grass: "grass",
  ground: "ground",
  ice: "ice",
  normal: "normal",
  poison: "poison",
  psychic: "psychic",
  rock: "rock",
  steel: "steel",
  water: "water",
} as const;

export const CORE_SCREEN_IDS = {
  lightScreen: "light-screen",
  luckyChant: "lucky-chant",
  reflect: "reflect",
} as const;

export const CORE_STATUS_IDS = {
  badlyPoisoned: "badly-poisoned",
  burn: "burn",
  freeze: "freeze",
  paralysis: "paralysis",
  poison: "poison",
  sleep: "sleep",
} as const;

export const CORE_VOLATILE_IDS = {
  aquaRing: "aqua-ring",
  bound: "bound",
  charged: "charged",
  confusion: "confusion",
  disable: "disable",
  encore: "encore",
  curse: "curse",
  destinyBond: "destiny-bond",
  charging: "charging",
  choiceLocked: "choice-locked",
  embargo: "embargo",
  healBlock: "heal-block",
  ingrain: "ingrain",
  flinch: "flinch",
  flying: "flying",
  infatuation: "infatuation",
  mist: "mist",
  noRetreat: "no-retreat",
  protect: "protect",
  rage: "rage",
  recharge: "recharge",
  leechSeed: "leech-seed",
  magnetRise: "magnet-rise",
  nightmare: "nightmare",
  shadowForceCharging: "shadow-force-charging",
  silkTrap: "silk-trap",
  justFrozen: "just-frozen",
  sleepCounter: "sleep-counter",
  trapped: "trapped",
  toxicCounter: "toxic-counter",
  yawn: "yawn",
  underground: "underground",
  smackDown: "smackdown",
  substitute: "substitute",
  uproar: "uproar",
  taunt: "taunt",
  unburden: "unburden",
} as const;

export const CORE_WEATHER_IDS = {
  harshSun: "harsh-sun",
  hail: "hail",
  rain: "rain",
  sand: "sand",
  snow: "snow",
  sun: "sun",
} as const;
