/**
 * Shared reference identifiers used across packages and tests.
 *
 * These remain lowercase string literals to match the repo's canonical entity ids.
 * The goal is to expose a single import surface for common domain ids/constants so
 * tests do not need to re-declare brittle file-local string bags.
 */

export const CORE_FIXED_POINT = {
  boost12: 4915,
  boost13: 5325,
  boost15: 6144,
  half: 2048,
  identity: 4096,
  gemBoost: 5325,
  resistHalf: 2048,
  spreadModifier: 3072,
  typeBoost: 4915,
} as const;

export const CORE_ABILITY_IDS = {
  blaze: "blaze",
  badDreams: "bad-dreams",
  defeatist: "defeatist",
  drizzle: "drizzle",
  drought: "drought",
  flashFire: "flash-fire",
  harvest: "harvest",
  klutz: "klutz",
  levitate: "levitate",
  intimidate: "intimidate",
  lightningRod: "lightning-rod",
  marvelScale: "marvel-scale",
  moldBreaker: "mold-breaker",
  moody: "moody",
  naturalCure: "natural-cure",
  cuteCharm: "cute-charm",
  pressure: "pressure",
  none: "none",
  pickup: "pickup",
  poisonHeal: "poison-heal",
  rainDish: "rain-dish",
  scrappy: "scrappy",
  shedSkin: "shed-skin",
  simple: "simple",
  skillLink: "skill-link",
  slowStart: "slow-start",
  solarPower: "solar-power",
  soundproof: "soundproof",
  speedBoost: "speed-boost",
  steadfast: "steadfast",
  static: "static",
  sturdy: "sturdy",
  torrent: "torrent",
  unburden: "unburden",
  wonderGuard: "wonder-guard",
} as const;

export const CORE_ITEM_IDS = {
  adamantOrb: "adamant-orb",
  airBalloon: "air-balloon",
  blackSludge: "black-sludge",
  chilanBerry: "chilan-berry",
  choiceBand: "choice-band",
  dampRock: "damp-rock",
  deepSeaScale: "deep-sea-scale",
  deepSeaTooth: "deep-sea-tooth",
  focusSash: "focus-sash",
  flameOrb: "flame-orb",
  griseousOrb: "griseous-orb",
  heatRock: "heat-rock",
  icyRock: "icy-rock",
  ironBall: "iron-ball",
  leftovers: "leftovers",
  lightBall: "light-ball",
  lustrousOrb: "lustrous-orb",
  normalGem: "normal-gem",
  occaBerry: "occa-berry",
  pokeBall: "poke-ball",
  smoothRock: "smooth-rock",
  toxicOrb: "toxic-orb",
  soulDew: "soul-dew",
  thickClub: "thick-club",
  yacheBerry: "yache-berry",
} as const;

export const CORE_MOVE_IDS = {
  aerialAce: "aerial-ace",
  acrobatics: "acrobatics",
  aquaRing: "aqua-ring",
  bind: "bind",
  bounce: "bounce",
  confusion: "confusion",
  doubleEdge: "double-edge",
  energyBall: "energy-ball",
  firePledge: "fire-pledge",
  flameCharge: "flame-charge",
  flamethrower: "flamethrower",
  focusBlast: "focus-blast",
  fly: "fly",
  futureSight: "future-sight",
  grassPledge: "grass-pledge",
  growl: "growl",
  headbutt: "headbutt",
  hex: "hex",
  leechSeed: "leech-seed",
  machPunch: "mach-punch",
  gravity: "gravity",
  luckyChant: "lucky-chant",
  perishSong: "perish-song",
  quickAttack: "quick-attack",
  pursuit: "pursuit",
  round: "round",
  skyDrop: "sky-drop",
  skyUppercut: "sky-uppercut",
  solarBeam: "solar-beam",
  sleepTalk: "sleep-talk",
  snore: "snore",
  stealthRock: "stealth-rock",
  struggle: "struggle",
  scratch: "scratch",
  surf: "surf",
  swift: "swift",
  sketch: "sketch",
  tackle: "tackle",
  thunderbolt: "thunderbolt",
  swordsDance: "swords-dance",
  triAttack: "tri-attack",
  wish: "wish",
  waterPledge: "water-pledge",
} as const;

export const CORE_MOVE_CATEGORIES = {
  physical: "physical",
  special: "special",
  status: "status",
} as const;

export const CORE_ABILITY_SLOTS = {
  normal1: "normal1",
  normal2: "normal2",
  hidden: "hidden",
} as const;

export const CORE_ABILITY_TRIGGER_IDS = {
  onSwitchIn: "on-switch-in",
  onSwitchOut: "on-switch-out",
  onBeforeMove: "on-before-move",
  onAfterMoveHit: "on-after-move-hit",
  onAfterMoveUsed: "on-after-move-used",
  onDamageTaken: "on-damage-taken",
  onDamageCalc: "on-damage-calc",
  onStatChange: "on-stat-change",
  onStatusInflicted: "on-status-inflicted",
  onWeatherChange: "on-weather-change",
  onTerrainChange: "on-terrain-change",
  onTurnEnd: "on-turn-end",
  onHpThreshold: "on-hp-threshold",
  onFaint: "on-faint",
  onContact: "on-contact",
  onCriticalHit: "on-critical-hit",
  onAccuracyCheck: "on-accuracy-check",
  onPriorityCheck: "on-priority-check",
  onTypeEffectiveness: "on-type-effectiveness",
  onItemUse: "on-item-use",
  passiveModifier: "passive-modifier",
  passiveImmunity: "passive-immunity",
  onFlinch: "on-flinch",
} as const;

export const CORE_ITEM_TRIGGER_IDS = {
  endOfTurn: "end-of-turn",
  onDamageTaken: "on-damage-taken",
  onContact: "on-contact",
  onHit: "on-hit",
  statBoostBetweenTurns: "stat-boost-between-turns",
} as const;

export const CORE_GENDERS = {
  male: "male",
  female: "female",
  genderless: "genderless",
} as const;

export const CORE_NATURE_IDS = {
  adamant: "adamant",
  bashful: "bashful",
  bold: "bold",
  brave: "brave",
  calm: "calm",
  careful: "careful",
  docile: "docile",
  gentle: "gentle",
  hardy: "hardy",
  hasty: "hasty",
  impish: "impish",
  jolly: "jolly",
  lax: "lax",
  lonely: "lonely",
  mild: "mild",
  modest: "modest",
  naive: "naive",
  naughty: "naughty",
  quiet: "quiet",
  quirky: "quirky",
  rash: "rash",
  relaxed: "relaxed",
  sassy: "sassy",
  serious: "serious",
  timid: "timid",
} as const;

export const CORE_HAZARD_IDS = {
  spikes: "spikes",
  stealthRock: "stealth-rock",
  stickyWeb: "sticky-web",
  toxicSpikes: "toxic-spikes",
} as const;

export const CORE_GIMMICK_IDS = {
  mega: "mega",
} as const;

export const CORE_END_OF_TURN_EFFECT_IDS = {
  bind: "bind",
  defrost: "defrost",
  disableCountdown: "disable-countdown",
  encoreCountdown: "encore-countdown",
  embargoCountdown: "embargo-countdown",
  flameOrbActivation: "flame-orb-activation",
  futureAttack: "future-attack",
  gravityCountdown: "gravity-countdown",
  grassyTerrainHeal: "grassy-terrain-heal",
  healBlockCountdown: "heal-block-countdown",
  healingItems: "healing-items",
  leftovers: "leftovers",
  magnetRiseCountdown: "magnet-rise-countdown",
  mysteryBerry: "mystery-berry",
  perishSong: "perish-song",
  safeguardCountdown: "safeguard-countdown",
  screenCountdown: "screen-countdown",
  slowStartCountdown: "slow-start-countdown",
  statBoostingItems: "stat-boosting-items",
  statusDamage: "status-damage",
  tauntCountdown: "taunt-countdown",
  tailwindCountdown: "tailwind-countdown",
  terrainCountdown: "terrain-countdown",
  toxicOrbActivation: "toxic-orb-activation",
  trickRoomCountdown: "trick-room-countdown",
  weatherCountdown: "weather-countdown",
  weatherDamage: "weather-damage",
  weatherHealing: "weather-healing",
  wish: "wish",
  yawnCountdown: "yawn-countdown",
} as const;

export const CORE_TERRAIN_IDS = {
  electric: "electric",
  electricTerrain: "electric-terrain",
  grassy: "grassy",
  grassyTerrain: "grassy-terrain",
  misty: "misty",
  mistyTerrain: "misty-terrain",
  psychic: "psychic",
  psychicTerrain: "psychic-terrain",
  testSource: "test",
} as const;

export const CORE_TYPE_IDS = {
  bug: "bug",
  dark: "dark",
  dragon: "dragon",
  electric: "electric",
  fairy: "fairy",
  fighting: "fighting",
  fire: "fire",
  flying: "flying",
  ghost: "ghost",
  grass: "grass",
  ground: "ground",
  ice: "ice",
  normal: "normal",
  poison: "poison",
  psychic: "psychic",
  rock: "rock",
  steel: "steel",
  water: "water",
} as const;

export const CORE_SCREEN_IDS = {
  auroraVeil: "aurora-veil",
  lightScreen: "light-screen",
  luckyChant: "lucky-chant",
  reflect: "reflect",
} as const;

export const CORE_STATUS_IDS = {
  badlyPoisoned: "badly-poisoned",
  burn: "burn",
  freeze: "freeze",
  paralysis: "paralysis",
  poison: "poison",
  sleep: "sleep",
} as const;

export const CORE_VOLATILE_IDS = {
  aquaRing: "aqua-ring",
  bound: "bound",
  charged: "charged",
  confusion: "confusion",
  disable: "disable",
  encore: "encore",
  curse: "curse",
  destinyBond: "destiny-bond",
  endure: "endure",
  charging: "charging",
  choiceLocked: "choice-locked",
  embargo: "embargo",
  flashFire: "flash-fire",
  focusEnergy: "focus-energy",
  healBlock: "heal-block",
  ingrain: "ingrain",
  flinch: "flinch",
  flying: "flying",
  infatuation: "infatuation",
  mist: "mist",
  noRetreat: "no-retreat",
  perishSong: "perish-song",
  protect: "protect",
  protosynthesis: "protosynthesis",
  quarkDrive: "quarkdrive",
  rage: "rage",
  recharge: "recharge",
  leechSeed: "leech-seed",
  saltCure: "salt-cure",
  magnetRise: "magnet-rise",
  nightmare: "nightmare",
  shadowForceCharging: "shadow-force-charging",
  silkTrap: "silk-trap",
  embodyAspectUsed: "embody-aspect-used",
  intrepidSwordUsed: "intrepid-sword-used",
  dauntlessShieldUsed: "dauntless-shield-used",
  proteanUsed: "protean-used",
  justFrozen: "just-frozen",
  shedTailSub: "shed-tail-sub",
  sleepCounter: "sleep-counter",
  trapped: "trapped",
  toxicCounter: "toxic-counter",
  yawn: "yawn",
  underground: "underground",
  smackDown: "smackdown",
  substitute: "substitute",
  telekinesis: "telekinesis",
  uproar: "uproar",
  taunt: "taunt",
  unburden: "unburden",
  underwater: "underwater",
} as const;

export const CORE_WEATHER_IDS = {
  heavyRain: "heavy-rain",
  harshSun: "harsh-sun",
  hail: "hail",
  rain: "rain",
  sand: "sand",
  snow: "snow",
  strongWinds: "strong-winds",
  sun: "sun",
} as const;
