import { describe, expect, it } from "vitest";
import { createGen9DataManager } from "../src/data/index.js";
import { Gen9Ruleset } from "../src/Gen9Ruleset.js";

describe("Gen9 smoke tests", () => {
  it("given Gen9Ruleset created with default DataManager, when checking generation, then returns 9", () => {
    // Source: Gen 9 is Generation IX (Scarlet/Violet), released November 2022
    const ruleset = new Gen9Ruleset();
    expect(ruleset.generation).toBe(9);
  });

  it("given Gen9Ruleset, when checking name, then contains 'Gen 9'", () => {
    // Source: Gen 9 is informally known as "Gen 9" or "Generation IX"
    const ruleset = new Gen9Ruleset();
    expect(ruleset.name).toContain("Gen 9");
  });

  it("given Gen9Ruleset, when getting available types, then returns 18 types", () => {
    // Source: Bulbapedia -- Gen 6+ has 18 types (Normal through Fairy)
    // Gen 9 did not add any new type effectiveness entries
    const ruleset = new Gen9Ruleset();
    expect(ruleset.getAvailableTypes()).toHaveLength(18);
  });

  it("given Gen9Ruleset, when checking hasTerrain, then returns true", () => {
    // Source: Showdown -- terrain mechanics exist in Gen 6+ including Gen 9
    const ruleset = new Gen9Ruleset();
    expect(ruleset.hasTerrain()).toBe(true);
  });

  it("given Gen9Ruleset, when checking shouldExecutePursuitPreSwitch, then returns false", () => {
    // Source: Bulbapedia -- Pursuit was removed in Gen 8 and remains absent in Gen 9
    const ruleset = new Gen9Ruleset();
    expect(ruleset.shouldExecutePursuitPreSwitch()).toBe(false);
  });

  it("given Gen9Ruleset, when checking getBattleGimmick for 'tera', then returns null (stub)", () => {
    // Source: Terastallization is the Gen 9 battle gimmick
    // Currently a stub -- will be implemented in Wave 2
    const ruleset = new Gen9Ruleset();
    expect(ruleset.getBattleGimmick("tera")).toBeNull();
  });

  it("given Gen9Ruleset, when checking getCritMultiplier, then returns 1.5", () => {
    // Source: Showdown sim/battle-actions.ts -- Gen 6+ crit multiplier is 1.5x
    // Source: Bulbapedia "Critical hit" -- multiplier unchanged since Gen 6
    const ruleset = new Gen9Ruleset();
    expect(ruleset.getCritMultiplier()).toBe(1.5);
  });

  it("given Gen9Ruleset, when checking getCritRateTable, then returns [24, 8, 2, 1]", () => {
    // Source: Showdown sim/battle-actions.ts -- Gen 6+ crit rate table
    // Stage 0: 1/24, Stage 1: 1/8, Stage 2: 1/2, Stage 3+: guaranteed
    const ruleset = new Gen9Ruleset();
    expect(ruleset.getCritRateTable()).toEqual([24, 8, 2, 1]);
  });

  it("given Gen9Ruleset, when checking recalculatesFutureAttackDamage, then returns true", () => {
    // Source: Bulbapedia -- Gen 5+ recalculates future attack damage at hit time
    const ruleset = new Gen9Ruleset();
    expect(ruleset.recalculatesFutureAttackDamage()).toBe(true);
  });

  it("given createGen9DataManager, when creating DataManager, then succeeds", () => {
    // Source: Data generated by tools/data-importer/src/import-gen.ts --gen=9
    const dm = createGen9DataManager();
    expect(dm).toBeDefined();
  });

  it("given Gen9Ruleset, when checking getAvailableHazards, then includes correct hazards", () => {
    // Source: Bulbapedia -- Gen 9 has Stealth Rock, Spikes, Toxic Spikes, Sticky Web
    // G-Max Steelsurge removed since Dynamax was removed in Gen 9
    const ruleset = new Gen9Ruleset();
    const hazards = ruleset.getAvailableHazards();
    expect(hazards).toContain("stealth-rock");
    expect(hazards).toContain("spikes");
    expect(hazards).toContain("toxic-spikes");
    expect(hazards).toContain("sticky-web");
    expect(hazards).not.toContain("gmax-steelsurge");
  });

  it("given Gen9Ruleset with custom DataManager, when created, then uses provided DataManager", () => {
    // Source: BaseRuleset constructor accepts optional DataManager
    const dm = createGen9DataManager();
    const ruleset = new Gen9Ruleset(dm);
    expect(ruleset.generation).toBe(9);
  });
});
