import type { MegaEvolutionData } from "../entities/species.js";

/**
 * Shared Mega Evolution data for Gen 6 and Gen 7.
 *
 * The item-to-form mapping is identical in both generations, so this lives in
 * core and is re-used by both per-gen gimmick implementations.
 */
export const MEGA_STONE_DATA: Readonly<Record<string, MegaEvolutionData>> = {
  venusaurite: {
    form: "mega-venusaur",
    item: "venusaurite",
    types: ["grass", "poison"],
    baseStats: { hp: 80, attack: 100, defense: 123, spAttack: 122, spDefense: 120, speed: 80 },
    ability: "thick-fat",
    baseSpeciesId: 3,
  },
  "charizardite-x": {
    form: "mega-charizard-x",
    item: "charizardite-x",
    types: ["fire", "dragon"],
    baseStats: { hp: 78, attack: 130, defense: 111, spAttack: 130, spDefense: 85, speed: 100 },
    ability: "tough-claws",
    baseSpeciesId: 6,
  },
  "charizardite-y": {
    form: "mega-charizard-y",
    item: "charizardite-y",
    types: ["fire", "flying"],
    baseStats: { hp: 78, attack: 104, defense: 78, spAttack: 159, spDefense: 115, speed: 100 },
    ability: "drought",
    baseSpeciesId: 6,
  },
  blastoisinite: {
    form: "mega-blastoise",
    item: "blastoisinite",
    types: ["water"],
    baseStats: { hp: 79, attack: 103, defense: 120, spAttack: 135, spDefense: 115, speed: 78 },
    ability: "mega-launcher",
    baseSpeciesId: 9,
  },
  beedrillite: {
    form: "mega-beedrill",
    item: "beedrillite",
    types: ["bug", "poison"],
    baseStats: { hp: 65, attack: 150, defense: 40, spAttack: 15, spDefense: 80, speed: 145 },
    ability: "adaptability",
    baseSpeciesId: 15,
  },
  pidgeotite: {
    form: "mega-pidgeot",
    item: "pidgeotite",
    types: ["normal", "flying"],
    baseStats: { hp: 83, attack: 80, defense: 80, spAttack: 135, spDefense: 80, speed: 121 },
    ability: "no-guard",
    baseSpeciesId: 18,
  },
  alakazite: {
    form: "mega-alakazam",
    item: "alakazite",
    types: ["psychic"],
    baseStats: { hp: 55, attack: 50, defense: 65, spAttack: 175, spDefense: 95, speed: 150 },
    ability: "trace",
    baseSpeciesId: 65,
  },
  gengarite: {
    form: "mega-gengar",
    item: "gengarite",
    types: ["ghost", "poison"],
    baseStats: { hp: 60, attack: 65, defense: 80, spAttack: 170, spDefense: 95, speed: 130 },
    ability: "shadow-tag",
    baseSpeciesId: 94,
  },
  kangaskhanite: {
    form: "mega-kangaskhan",
    item: "kangaskhanite",
    types: ["normal"],
    baseStats: { hp: 105, attack: 125, defense: 100, spAttack: 60, spDefense: 100, speed: 100 },
    ability: "parental-bond",
    baseSpeciesId: 115,
  },
  pinsirite: {
    form: "mega-pinsir",
    item: "pinsirite",
    types: ["bug", "flying"],
    baseStats: { hp: 65, attack: 155, defense: 120, spAttack: 65, spDefense: 90, speed: 105 },
    ability: "aerilate",
    baseSpeciesId: 127,
  },
  gyaradosite: {
    form: "mega-gyarados",
    item: "gyaradosite",
    types: ["water", "dark"],
    baseStats: { hp: 95, attack: 155, defense: 109, spAttack: 70, spDefense: 130, speed: 81 },
    ability: "mold-breaker",
    baseSpeciesId: 130,
  },
  aerodactylite: {
    form: "mega-aerodactyl",
    item: "aerodactylite",
    types: ["rock", "flying"],
    baseStats: { hp: 80, attack: 135, defense: 85, spAttack: 70, spDefense: 95, speed: 150 },
    ability: "tough-claws",
    baseSpeciesId: 142,
  },
  "mewtwonite-x": {
    form: "mega-mewtwo-x",
    item: "mewtwonite-x",
    types: ["psychic", "fighting"],
    baseStats: { hp: 106, attack: 190, defense: 100, spAttack: 154, spDefense: 100, speed: 130 },
    ability: "steadfast",
    baseSpeciesId: 150,
  },
  "mewtwonite-y": {
    form: "mega-mewtwo-y",
    item: "mewtwonite-y",
    types: ["psychic"],
    baseStats: { hp: 106, attack: 150, defense: 70, spAttack: 194, spDefense: 120, speed: 140 },
    ability: "insomnia",
    baseSpeciesId: 150,
  },
  ampharosite: {
    form: "mega-ampharos",
    item: "ampharosite",
    types: ["electric", "dragon"],
    baseStats: { hp: 90, attack: 95, defense: 105, spAttack: 165, spDefense: 110, speed: 45 },
    ability: "mold-breaker",
    baseSpeciesId: 181,
  },
  steelixite: {
    form: "mega-steelix",
    item: "steelixite",
    types: ["steel", "ground"],
    baseStats: { hp: 75, attack: 125, defense: 230, spAttack: 55, spDefense: 95, speed: 30 },
    ability: "sand-force",
    baseSpeciesId: 208,
  },
  scizorite: {
    form: "mega-scizor",
    item: "scizorite",
    types: ["bug", "steel"],
    baseStats: { hp: 70, attack: 150, defense: 140, spAttack: 65, spDefense: 100, speed: 75 },
    ability: "technician",
    baseSpeciesId: 212,
  },
  heracronite: {
    form: "mega-heracross",
    item: "heracronite",
    types: ["bug", "fighting"],
    baseStats: { hp: 80, attack: 185, defense: 115, spAttack: 40, spDefense: 105, speed: 75 },
    ability: "skill-link",
    baseSpeciesId: 214,
  },
  houndoominite: {
    form: "mega-houndoom",
    item: "houndoominite",
    types: ["dark", "fire"],
    baseStats: { hp: 75, attack: 90, defense: 90, spAttack: 140, spDefense: 90, speed: 115 },
    ability: "solar-power",
    baseSpeciesId: 229,
  },
  tyranitarite: {
    form: "mega-tyranitar",
    item: "tyranitarite",
    types: ["rock", "dark"],
    baseStats: { hp: 100, attack: 164, defense: 150, spAttack: 95, spDefense: 120, speed: 71 },
    ability: "sand-stream",
    baseSpeciesId: 248,
  },
  sceptilite: {
    form: "mega-sceptile",
    item: "sceptilite",
    types: ["grass", "dragon"],
    baseStats: { hp: 70, attack: 110, defense: 75, spAttack: 145, spDefense: 85, speed: 145 },
    ability: "lightning-rod",
    baseSpeciesId: 254,
  },
  blazikenite: {
    form: "mega-blaziken",
    item: "blazikenite",
    types: ["fire", "fighting"],
    baseStats: { hp: 80, attack: 160, defense: 80, spAttack: 130, spDefense: 80, speed: 100 },
    ability: "speed-boost",
    baseSpeciesId: 257,
  },
  swampertite: {
    form: "mega-swampert",
    item: "swampertite",
    types: ["water", "ground"],
    baseStats: { hp: 100, attack: 150, defense: 110, spAttack: 95, spDefense: 110, speed: 70 },
    ability: "swift-swim",
    baseSpeciesId: 260,
  },
  gardevoirite: {
    form: "mega-gardevoir",
    item: "gardevoirite",
    types: ["psychic", "fairy"],
    baseStats: { hp: 68, attack: 85, defense: 65, spAttack: 165, spDefense: 135, speed: 100 },
    ability: "pixilate",
    baseSpeciesId: 282,
  },
  sablenite: {
    form: "mega-sableye",
    item: "sablenite",
    types: ["dark", "ghost"],
    baseStats: { hp: 50, attack: 85, defense: 125, spAttack: 85, spDefense: 115, speed: 20 },
    ability: "magic-bounce",
    baseSpeciesId: 302,
  },
  mawilite: {
    form: "mega-mawile",
    item: "mawilite",
    types: ["steel", "fairy"],
    baseStats: { hp: 50, attack: 105, defense: 125, spAttack: 55, spDefense: 95, speed: 50 },
    ability: "huge-power",
    baseSpeciesId: 303,
  },
  aggronite: {
    form: "mega-aggron",
    item: "aggronite",
    types: ["steel"],
    baseStats: { hp: 70, attack: 140, defense: 230, spAttack: 60, spDefense: 80, speed: 50 },
    ability: "filter",
    baseSpeciesId: 306,
  },
  manectite: {
    form: "mega-manectric",
    item: "manectite",
    types: ["electric"],
    baseStats: { hp: 70, attack: 75, defense: 80, spAttack: 135, spDefense: 80, speed: 135 },
    ability: "intimidate",
    baseSpeciesId: 310,
  },
  cameruptite: {
    form: "mega-camerupt",
    item: "cameruptite",
    types: ["fire", "ground"],
    baseStats: { hp: 70, attack: 120, defense: 100, spAttack: 145, spDefense: 105, speed: 20 },
    ability: "sheer-force",
    baseSpeciesId: 323,
  },
  altarianite: {
    form: "mega-altaria",
    item: "altarianite",
    types: ["dragon", "fairy"],
    baseStats: { hp: 75, attack: 110, defense: 110, spAttack: 110, spDefense: 105, speed: 80 },
    ability: "pixilate",
    baseSpeciesId: 334,
  },
  banettite: {
    form: "mega-banette",
    item: "banettite",
    types: ["ghost"],
    baseStats: { hp: 64, attack: 165, defense: 75, spAttack: 93, spDefense: 83, speed: 75 },
    ability: "prankster",
    baseSpeciesId: 354,
  },
  absolite: {
    form: "mega-absol",
    item: "absolite",
    types: ["dark"],
    baseStats: { hp: 65, attack: 150, defense: 60, spAttack: 115, spDefense: 60, speed: 115 },
    ability: "magic-bounce",
    baseSpeciesId: 359,
  },
  glalitite: {
    form: "mega-glalie",
    item: "glalitite",
    types: ["ice"],
    baseStats: { hp: 80, attack: 120, defense: 80, spAttack: 120, spDefense: 80, speed: 100 },
    ability: "refrigerate",
    baseSpeciesId: 362,
  },
  salamencite: {
    form: "mega-salamence",
    item: "salamencite",
    types: ["dragon", "flying"],
    baseStats: { hp: 95, attack: 145, defense: 130, spAttack: 120, spDefense: 90, speed: 120 },
    ability: "aerilate",
    baseSpeciesId: 373,
  },
  metagrossite: {
    form: "mega-metagross",
    item: "metagrossite",
    types: ["steel", "psychic"],
    baseStats: { hp: 80, attack: 145, defense: 150, spAttack: 105, spDefense: 110, speed: 110 },
    ability: "tough-claws",
    baseSpeciesId: 376,
  },
  latiasite: {
    form: "mega-latias",
    item: "latiasite",
    types: ["dragon", "psychic"],
    baseStats: { hp: 80, attack: 100, defense: 120, spAttack: 140, spDefense: 150, speed: 110 },
    ability: "levitate",
    baseSpeciesId: 380,
  },
  latiosite: {
    form: "mega-latios",
    item: "latiosite",
    types: ["dragon", "psychic"],
    baseStats: { hp: 80, attack: 130, defense: 100, spAttack: 160, spDefense: 120, speed: 110 },
    ability: "levitate",
    baseSpeciesId: 381,
  },
  lopunnite: {
    form: "mega-lopunny",
    item: "lopunnite",
    types: ["normal", "fighting"],
    baseStats: { hp: 65, attack: 136, defense: 94, spAttack: 54, spDefense: 96, speed: 135 },
    ability: "scrappy",
    baseSpeciesId: 428,
  },
  garchompite: {
    form: "mega-garchomp",
    item: "garchompite",
    types: ["dragon", "ground"],
    baseStats: { hp: 108, attack: 170, defense: 115, spAttack: 120, spDefense: 95, speed: 92 },
    ability: "sand-force",
    baseSpeciesId: 445,
  },
  lucarionite: {
    form: "mega-lucario",
    item: "lucarionite",
    types: ["fighting", "steel"],
    baseStats: { hp: 70, attack: 145, defense: 88, spAttack: 140, spDefense: 70, speed: 112 },
    ability: "adaptability",
    baseSpeciesId: 448,
  },
  abomasite: {
    form: "mega-abomasnow",
    item: "abomasite",
    types: ["grass", "ice"],
    baseStats: { hp: 90, attack: 132, defense: 105, spAttack: 132, spDefense: 105, speed: 30 },
    ability: "snow-warning",
    baseSpeciesId: 460,
  },
  galladite: {
    form: "mega-gallade",
    item: "galladite",
    types: ["psychic", "fighting"],
    baseStats: { hp: 68, attack: 165, defense: 95, spAttack: 65, spDefense: 115, speed: 110 },
    ability: "inner-focus",
    baseSpeciesId: 475,
  },
  audinite: {
    form: "mega-audino",
    item: "audinite",
    types: ["normal", "fairy"],
    baseStats: { hp: 103, attack: 60, defense: 126, spAttack: 80, spDefense: 126, speed: 50 },
    ability: "healer",
    baseSpeciesId: 531,
  },
  diancite: {
    form: "mega-diancie",
    item: "diancite",
    types: ["rock", "fairy"],
    baseStats: { hp: 50, attack: 160, defense: 110, spAttack: 160, spDefense: 110, speed: 110 },
    ability: "magic-bounce",
    baseSpeciesId: 719,
  },
  sharpedonite: {
    form: "mega-sharpedo",
    item: "sharpedonite",
    types: ["water", "dark"],
    baseStats: { hp: 70, attack: 140, defense: 70, spAttack: 110, spDefense: 65, speed: 105 },
    ability: "strong-jaw",
    baseSpeciesId: 319,
  },
  slowbronite: {
    form: "mega-slowbro",
    item: "slowbronite",
    types: ["water", "psychic"],
    baseStats: { hp: 95, attack: 75, defense: 180, spAttack: 130, spDefense: 80, speed: 30 },
    ability: "shell-armor",
    baseSpeciesId: 80,
  },
  medichamite: {
    form: "mega-medicham",
    item: "medichamite",
    types: ["fighting", "psychic"],
    baseStats: { hp: 60, attack: 100, defense: 85, spAttack: 80, spDefense: 85, speed: 100 },
    ability: "pure-power",
    baseSpeciesId: 308,
  },
} as const;
