export const GEN8_TEST_VALUES = {
  battle: {
    singles: "singles",
  },
  pokemon: {
    uid: "test",
    nature: "hardy",
    ability: "none",
    abilitySlot: "normal1",
    gender: "male",
    pokeball: "pokeball",
    defaultType: "normal",
  },
  abilities: {
    klutz: "klutz",
  },
  volatiles: {
    embargo: "embargo",
  },
  fixedPoint: {
    neutral: 4096,
    boost12: 4915,
    boost13: 5325,
    boost15: 6144,
    resistHalf: 2048,
  },
  expectedAmounts: {
    minimum: 1,
    lifeOrbRecoil200: 20,
    lifeOrbRecoil160: 16,
    lifeOrbRecoil300: 30,
    leftoversHeal320: 20,
    leftoversHeal160: 10,
    leftoversHeal200: 12,
    blackSludgeHeal320: 20,
    blackSludgeHeal200: 12,
    blackSludgeDamage320: 40,
    blackSludgeDamage200: 25,
    rockyHelmetDamage300: 50,
    rockyHelmetDamage200: 33,
    evioliteBoost: 6144,
  },
  hp: {
    min: 1,
    leftOversRecoil: 160,
    lifeOrbRecoil: 200,
    rockyHelmetDamage: 300,
    blackSludgeHeal: 320,
    airBalloonPop: 400,
  },
  types: {
    normal: "normal",
    fire: "fire",
    water: "water",
    ice: "ice",
    poison: "poison",
    dark: "dark",
  },
  categories: {
    physical: "physical",
    special: "special",
    status: "status",
  },
  items: {
    assaultVest: "assault-vest",
    airBalloon: "air-balloon",
    blackSludge: "black-sludge",
    blunderPolicy: "blunder-policy",
    charcoal: "charcoal",
    chilanBerry: "chilan-berry",
    choiceBand: "choice-band",
    choiceScarf: "choice-scarf",
    choiceSpecs: "choice-specs",
    ejectPack: "eject-pack",
    eviolite: "eviolite",
    flamePlate: "flame-plate",
    focusSash: "focus-sash",
    heavyDutyBoots: "heavy-duty-boots",
    ironBall: "iron-ball",
    leftovers: "leftovers",
    lifeOrb: "life-orb",
    potion: "potion",
    mysticWater: "mystic-water",
    occaBerry: "occa-berry",
    rockyHelmet: "rocky-helmet",
    roomService: "room-service",
    seaIncense: "sea-incense",
    silkScarf: "silk-scarf",
    throatSpray: "throat-spray",
    utilityUmbrella: "utility-umbrella",
    yacheBerry: "yache-berry",
  },
  moves: {
    tackle: "tackle",
    surf: "surf",
    flamethrower: "flamethrower",
    hyperVoice: "hyper-voice",
  },
} as const;
