// @pokemon-lib-ts/battle — BattleEngine, GenerationRuleset interface, BaseRuleset, BattleState, BattleEvent stream, AI controllers

// AI
export type { AIController } from "./ai";
export { RandomAI } from "./ai";
// Context
export type {
  AbilityContext,
  AbilityEffect,
  AbilityEffectType,
  AbilityResult,
  AccuracyContext,
  AvailableMove,
  BagItemResult,
  BattleConfig,
  BattleGimmick,
  CatchResult,
  CritContext,
  DamageBreakdown,
  DamageContext,
  DamageResult,
  EndOfTurnEffect,
  EntryHazardResult,
  ExpContext,
  ItemContext,
  ItemEffect,
  ItemEffectType,
  ItemResult,
  MoveEffectContext,
  MoveEffectResult,
  TerrainEffectResult,
  TrainerDataRef,
  ValidationResult,
  WeatherEffectResult,
} from "./context";
// Data
export {
  BASE_PINCH_ABILITY_TYPES,
  BASE_PLATE_ITEMS,
  BASE_TYPE_BOOST_ITEMS,
} from "./data";
// Engine
export { BattleEngine } from "./engine";
// Events
export type {
  AbilityActivateEvent,
  BattleAction,
  BattleEndEvent,
  BattleEvent,
  BattleEventEmitter,
  BattleEventListener,
  BattleStartEvent,
  CatchAttemptEvent,
  CriticalHitEvent,
  DamageEvent,
  DynamaxEndEvent,
  DynamaxEvent,
  EffectivenessEvent,
  EngineWarningEvent,
  ExpGainEvent,
  FaintEvent,
  FleeAttemptEvent,
  HazardClearEvent,
  HazardSetEvent,
  HealEvent,
  ItemAction,
  ItemActivateEvent,
  ItemConsumedEvent,
  LevelUpEvent,
  MegaEvolveEvent,
  MessageEvent,
  MoveAction,
  MoveFailEvent,
  MoveMissEvent,
  MoveStartEvent,
  PokemonSnapshot,
  RechargeAction,
  RunAction,
  ScreenEndEvent,
  ScreenSetEvent,
  StatChangeEvent,
  StatusCureEvent,
  StatusInflictEvent,
  StruggleAction,
  SwitchAction,
  SwitchInEvent,
  SwitchOutEvent,
  TerastallizeEvent,
  TerrainEndEvent,
  TerrainSetEvent,
  TurnStartEvent,
  VolatileEndEvent,
  VolatileStartEvent,
  WeatherEndEvent,
  WeatherSetEvent,
  ZMoveEvent,
} from "./events";
// Ruleset
export type {
  AbilitySystem,
  BagItemSystem,
  BattleGimmickType,
  CatchSystem,
  CriticalHitSystem,
  DamageSystem,
  EndOfTurnSystem,
  ExpDistributionSystem,
  ExpRecipient,
  ExpRecipientSelectionContext,
  FleeSystem,
  GenerationRuleset,
  HazardSystem,
  ItemSystem,
  MoveSystem,
  StatCalculator,
  StatusSystem,
  SwitchSystem,
  TerrainSystem,
  TurnOrderSystem,
  TypeSystem,
  ValidationSystem,
  WeatherSystem,
} from "./ruleset";
export { BaseRuleset, GenerationRegistry, generations } from "./ruleset";
// State
export type {
  ActivePokemon,
  BattleFormat,
  BattlePhase,
  BattleSide,
  BattleState,
  EntryHazardState,
  FutureAttackState,
  ScreenState,
  TerrainState,
  TurnRecord,
  VolatileStatusState,
  WeatherState,
} from "./state";

// Utils
export {
  createPokemonSnapshot,
  getEffectiveStatStage,
  getPokemonName,
} from "./utils";
