import { CORE_ITEM_IDS, CORE_TYPE_IDS } from "@pokemon-lib-ts/core";
import { describe, expect, it } from "vitest";
import {
  createGen8DataManager,
  GEN8_ABILITY_IDS,
  GEN8_ITEM_IDS,
  GEN8_MOVE_IDS,
  GEN8_SPECIES_IDS,
} from "../src";

const SPECIES = GEN8_SPECIES_IDS;
const MOVES = GEN8_MOVE_IDS;
const ABILITIES = GEN8_ABILITY_IDS;
const ITEMS = GEN8_ITEM_IDS;
const TYPES = CORE_TYPE_IDS;
const GEN8_TYPE_NAMES = [
  TYPES.normal,
  TYPES.fire,
  TYPES.water,
  TYPES.electric,
  TYPES.grass,
  TYPES.ice,
  TYPES.fighting,
  TYPES.poison,
  TYPES.ground,
  TYPES.flying,
  TYPES.psychic,
  TYPES.bug,
  TYPES.rock,
  TYPES.ghost,
  TYPES.dragon,
  TYPES.dark,
  TYPES.steel,
  TYPES.fairy,
] as const;

describe("Gen 8 DataManager -- data loading", () => {
  // ---------------------------------------------------------------------------
  // Pokemon
  // ---------------------------------------------------------------------------

  it("given gen8 data files, when loading DataManager, then loads at least 600 Pokemon", () => {
    // Source: Data generated by tools/data-importer/src/import-gen.ts --gen=8
    // Gen 8 (Sword/Shield) has a regional dex -- many older Pokemon are not
    // available. The importer pulls species #1-#905 but skips those not in
    // Showdown's Gen 8 data. Expect at least 600 species.
    const dm = createGen8DataManager();
    expect(dm.getAllSpecies().length).toBeGreaterThanOrEqual(600);
  });

  it("given gen8 data files, when loading DataManager, then loads exactly 664 Pokemon", () => {
    // Source: Data generated by tools/data-importer/src/import-gen.ts --gen=8
    // @pkmn/data Gen 8 iteration yields 664 base-form species (excludes
    // Pokemon cut from Sword/Shield's regional dex).
    const dm = createGen8DataManager();
    expect(dm.getAllSpecies().length).toBe(664);
  });

  it("given gen8 data files, when loading DataManager, then loads 646 moves", () => {
    // Source: @pkmn/data gen8 move count (646 moves available in Gen 8)
    const dm = createGen8DataManager();
    expect(dm.getAllMoves().length).toBe(646);
  });

  it("given gen8 data files, when loading DataManager, then loads 267 abilities", () => {
    // Source: @pkmn/data gen8 ability count (267 abilities through Gen 8)
    // Gen 8 added 34 new abilities (234-267) on top of Gen 7's 233.
    const dm = createGen8DataManager();
    expect(dm.getAllAbilities().length).toBe(267);
  });

  it("given gen8 data files, when loading DataManager, then loads 25 natures", () => {
    // Source: 25 natures introduced in Gen 3, unchanged through all generations
    const dm = createGen8DataManager();
    expect(dm.getAllNatures().length).toBe(25);
  });

  it("given gen8 data files, when loading DataManager, then loads 354 items", () => {
    // Source: @pkmn/data gen8 item count (354 items)
    const dm = createGen8DataManager();
    expect(dm.getAllItems().length).toBe(354);
  });

  // ---------------------------------------------------------------------------
  // Type chart
  // ---------------------------------------------------------------------------

  it("given gen8 type chart, when checking type count, then has exactly 18 types", () => {
    // Source: Gen 8 has 18 types (same as Gen 6-7, no new types added)
    // Source: Bulbapedia -- https://bulbapedia.bulbagarden.net/wiki/Generation_VIII
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(Object.keys(chart).length).toBe(18);
  });

  it("given gen8 type chart, when checking for Fairy, then Fairy exists", () => {
    // Source: Fairy type introduced in Gen 6, present in Gen 8
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart).toHaveProperty(TYPES.fairy);
  });

  it("given gen8 type chart, when checking Fairy attacking Dragon, then Dragon is weak to Fairy (2x)", () => {
    // Source: Bulbapedia -- Fairy is super effective against Dragon
    // Source: references/pokemon-showdown/data/typechart.ts
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart[TYPES.fairy]?.[TYPES.dragon]).toBe(2);
  });

  it("given gen8 type chart, when checking Dragon attacking Fairy, then Fairy is immune to Dragon (0x)", () => {
    // Source: Bulbapedia -- Fairy is immune to Dragon-type moves
    // Source: references/pokemon-showdown/data/typechart.ts
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart[TYPES.dragon]?.[TYPES.fairy]).toBe(0);
  });

  it("given gen8 type chart, when checking Dark attacking Steel, then Steel is neutral to Dark (1x)", () => {
    // Source: references/pokemon-showdown/data/typechart.ts
    // In Gen 6+, Steel no longer resists Dark (was 0.5x in Gen 2-5)
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart[TYPES.dark]?.[TYPES.steel]).toBe(1);
  });

  it("given gen8 type chart, when checking Ghost attacking Steel, then Steel is neutral to Ghost (1x)", () => {
    // Source: references/pokemon-showdown/data/typechart.ts
    // In Gen 6+, Steel no longer resists Ghost (was 0.5x in Gen 2-5)
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart[TYPES.ghost]?.[TYPES.steel]).toBe(1);
  });

  it("given gen8 type chart, when checking Normal attacking Ghost, then Ghost is immune (0x)", () => {
    // Source: Bulbapedia -- Normal-type moves do not affect Ghost-type Pokemon
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart[TYPES.normal]?.[TYPES.ghost]).toBe(0);
  });

  it("given gen8 type chart, when checking Steel attacking Fairy, then Fairy is weak to Steel (2x)", () => {
    // Source: Bulbapedia -- Steel is super effective against Fairy
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart[TYPES.steel]?.[TYPES.fairy]).toBe(2);
  });

  // ---------------------------------------------------------------------------
  // Gen 8 Pokemon species
  // ---------------------------------------------------------------------------

  it("given gen8 data, when looking up Pikachu, then base stats match Bulbapedia", () => {
    // Source: Bulbapedia -- Pikachu (#25) base stats (unchanged since Gen 6):
    // HP=35, Atk=55, Def=40, SpA=50, SpD=50, Spe=90
    const dm = createGen8DataManager();
    const pikachu = dm.getSpecies(SPECIES.pikachu);
    expect(pikachu.baseStats.hp).toBe(35);
    expect(pikachu.baseStats.attack).toBe(55);
    expect(pikachu.baseStats.defense).toBe(40);
    expect(pikachu.baseStats.spAttack).toBe(50);
    expect(pikachu.baseStats.spDefense).toBe(50);
    expect(pikachu.baseStats.speed).toBe(90);
  });

  it("given gen8 data, when looking up Grookey, then types are Grass", () => {
    // Source: Bulbapedia -- Grookey (#810) is a pure Grass-type
    // First starter of Gen 8 (Sword/Shield)
    const dm = createGen8DataManager();
    const grookey = dm.getSpecies(SPECIES.grookey);
    expect(grookey.types).toEqual([TYPES.grass]);
  });

  it("given gen8 data, when looking up Cinderace, then type is Fire", () => {
    // Source: Bulbapedia -- Cinderace (#815) is a pure Fire-type
    const dm = createGen8DataManager();
    const cinderace = dm.getSpecies(SPECIES.cinderace);
    expect(cinderace.types).toEqual([TYPES.fire]);
  });

  it("given gen8 data, when looking up Dragapult, then types are Dragon/Ghost", () => {
    // Source: Bulbapedia -- Dragapult (#887) is Dragon/Ghost
    const dm = createGen8DataManager();
    const dragapult = dm.getSpecies(SPECIES.dragapult);
    expect(dragapult.types).toEqual([TYPES.dragon, TYPES.ghost]);
  });

  it("given gen8 data, when looking up Dragapult, then base stats match Bulbapedia", () => {
    // Source: Bulbapedia -- Dragapult (#887) base stats:
    // HP=88, Atk=120, Def=75, SpA=100, SpD=75, Spe=142
    const dm = createGen8DataManager();
    const dragapult = dm.getSpecies(SPECIES.dragapult);
    expect(dragapult.baseStats.hp).toBe(88);
    expect(dragapult.baseStats.attack).toBe(120);
    expect(dragapult.baseStats.defense).toBe(75);
    expect(dragapult.baseStats.spAttack).toBe(100);
    expect(dragapult.baseStats.spDefense).toBe(75);
    expect(dragapult.baseStats.speed).toBe(142);
  });

  it("given gen8 data, when looking up Zacian, then types are Fairy", () => {
    // Source: Bulbapedia -- Zacian (#888) base form is a pure Fairy-type
    // (Crowned form is Fairy/Steel, but base form is mono-Fairy)
    const dm = createGen8DataManager();
    const zacian = dm.getSpecies(SPECIES.zacian);
    expect(zacian.types).toEqual([TYPES.fairy]);
  });

  it("given gen8 data, when looking up Zamazenta, then types are Fighting", () => {
    // Source: Bulbapedia -- Zamazenta (#889) base form is a pure Fighting-type
    // (Crowned form is Fighting/Steel, but base form is mono-Fighting)
    const dm = createGen8DataManager();
    const zamazenta = dm.getSpecies(SPECIES.zamazenta);
    expect(zamazenta.types).toEqual([TYPES.fighting]);
  });

  it("given gen8 data, when looking up Eternatus, then types are Poison/Dragon", () => {
    // Source: Bulbapedia -- Eternatus (#890) is Poison/Dragon
    const dm = createGen8DataManager();
    const eternatus = dm.getSpecies(SPECIES.eternatus);
    expect(eternatus.types).toEqual([TYPES.poison, TYPES.dragon]);
  });

  // ---------------------------------------------------------------------------
  // Gen 8 moves
  // ---------------------------------------------------------------------------

  it("given gen8 moves, when looking up Behemoth Blade, then power is 100 and type is Steel", () => {
    // Source: Bulbapedia -- Behemoth Blade: Steel-type, 100 power, physical
    // Signature move of Zacian (Crowned Sword form)
    const dm = createGen8DataManager();
    const move = dm.getMove(MOVES.behemothBlade);
    expect(move.power).toBe(100);
    expect(move.type).toBe(TYPES.steel);
    expect(move.category).toBe("physical");
  });

  it("given gen8 moves, when looking up Pyro Ball, then power is 120 and type is Fire", () => {
    // Source: Bulbapedia -- Pyro Ball: Fire-type, 120 power, physical
    // Signature move of Cinderace
    const dm = createGen8DataManager();
    const move = dm.getMove(MOVES.pyroBall);
    expect(move.power).toBe(120);
    expect(move.type).toBe(TYPES.fire);
    expect(move.category).toBe("physical");
  });

  it("given gen8 moves, when looking up Grassy Glide, then power is 55 and type is Grass", () => {
    // Source: current Gen 8 data bundle imported into packages/gen8/data/moves.json.
    // In this repo's Gen 8 data, Grassy Glide remains its Gen 8 value: 70 BP.
    const dm = createGen8DataManager();
    const move = dm.getMove(MOVES.grassyGlide);
    expect(move.type).toBe(TYPES.grass);
    expect(move.category).toBe("physical");
    expect(move.power).toBe(70);
  });

  it("given gen8 moves, when looking up Wicked Blow, then power is 80 and type is Dark", () => {
    // Source: Bulbapedia -- Wicked Blow: Dark-type, 80 power, physical (buffed from 75 in Gen 9)
    // Signature move of Urshifu (Single Strike Style)
    // Always results in a critical hit
    const dm = createGen8DataManager();
    const move = dm.getMove(MOVES.wickedBlow);
    expect(move.power).toBe(80);
    expect(move.type).toBe(TYPES.dark);
    expect(move.category).toBe("physical");
  });

  // ---------------------------------------------------------------------------
  // Gen 8 abilities
  // ---------------------------------------------------------------------------

  it("given gen8 abilities, when looking up Libero, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Libero introduced in Gen 8 (Cinderace's hidden ability)
    // Changes the user's type to match the move being used before executing
    const dm = createGen8DataManager();
    const ability = dm.getAbility(ABILITIES.libero);
    expect(ability.id).toBe(ABILITIES.libero);
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Intrepid Sword, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Intrepid Sword introduced in Gen 8
    // Zacian's signature ability: raises Attack by one stage on switch-in
    const dm = createGen8DataManager();
    const ability = dm.getAbility(ABILITIES.intrepidSword);
    expect(ability.id).toBe(ABILITIES.intrepidSword);
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Dauntless Shield, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Dauntless Shield introduced in Gen 8
    // Zamazenta's signature ability: raises Defense by one stage on switch-in
    const dm = createGen8DataManager();
    const ability = dm.getAbility(ABILITIES.dauntlessShield);
    expect(ability.id).toBe(ABILITIES.dauntlessShield);
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Gorilla Tactics, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Gorilla Tactics introduced in Gen 8
    // Darmanitan-Galar's ability: boosts Attack by 1.5x but locks into one move
    const dm = createGen8DataManager();
    const ability = dm.getAbility(ABILITIES.gorillaTactics);
    expect(ability.id).toBe(ABILITIES.gorillaTactics);
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Neutralizing Gas, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Neutralizing Gas introduced in Gen 8
    // Weezing-Galar's ability: suppresses all other abilities while active
    const dm = createGen8DataManager();
    const ability = dm.getAbility(ABILITIES.neutralizingGas);
    expect(ability.id).toBe(ABILITIES.neutralizingGas);
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Ice Scales, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Ice Scales introduced in Gen 8
    // Frosmoth's ability: halves damage from special moves
    const dm = createGen8DataManager();
    const ability = dm.getAbility(ABILITIES.iceScales);
    expect(ability.id).toBe(ABILITIES.iceScales);
    expect(ability.generation).toBe(8);
  });

  // ---------------------------------------------------------------------------
  // Gen 8 items
  // ---------------------------------------------------------------------------

  it("given gen8 items, when loading items, then Leftovers still exists", () => {
    // Source: Leftovers has existed since Gen 2, still present in Gen 8
    const dm = createGen8DataManager();
    const item = dm.getItem(CORE_ITEM_IDS.leftovers);
    expect(item.id).toBe(CORE_ITEM_IDS.leftovers);
  });

  it("given gen8 items, when loading items, then Choice Scarf exists", () => {
    // Source: Choice Scarf introduced in Gen 4, still present in Gen 8
    const dm = createGen8DataManager();
    const item = dm.getItem(ITEMS.choiceScarf);
    expect(item.id).toBe(ITEMS.choiceScarf);
  });

  it("given gen8 items, when loading items, then Heavy-Duty Boots exists", () => {
    // Source: Bulbapedia -- Heavy-Duty Boots introduced in Gen 8
    // Protects holder from entry hazards
    const dm = createGen8DataManager();
    const item = dm.getItem(ITEMS.heavyDutyBoots);
    expect(item.id).toBe(ITEMS.heavyDutyBoots);
  });

  it("given gen8 items, when loading items, then Utility Umbrella exists", () => {
    // Source: Bulbapedia -- Utility Umbrella introduced in Gen 8
    // The effects of weather are negated for the holder
    const dm = createGen8DataManager();
    const item = dm.getItem(ITEMS.utilityUmbrella);
    expect(item.id).toBe(ITEMS.utilityUmbrella);
  });

  // ---------------------------------------------------------------------------
  // Structural validation
  // ---------------------------------------------------------------------------

  it("given gen8 moves, when inspecting any move, then required fields are present", () => {
    // All moves must have id, type, category, pp, and priority
    const dm = createGen8DataManager();
    const moves = dm.getAllMoves();
    for (const move of moves) {
      expect(move.id.length).toBeGreaterThan(0);
      expect(GEN8_TYPE_NAMES).toContain(move.type);
      expect(["physical", "special", "status"]).toContain(move.category);
      expect(move.pp).toBeGreaterThan(0);
      expect(typeof move.priority).toBe("number");
    }
  });

  it("given representative gen8 species, when inspecting their records, then each has the expected structural fields", () => {
    const dm = createGen8DataManager();
    expect(dm.getSpecies(SPECIES.pikachu)).toEqual(
      expect.objectContaining({
        id: 25,
        name: "pikachu",
        displayName: "Pikachu",
        types: [TYPES.electric],
        baseStats: expect.objectContaining({
          hp: 35,
          attack: 55,
          defense: 40,
          spAttack: 50,
          spDefense: 50,
          speed: 90,
        }),
      }),
    );
    expect(dm.getSpecies(SPECIES.grookey)).toEqual(
      expect.objectContaining({
        id: 810,
        name: "grookey",
        displayName: "Grookey",
        types: [TYPES.grass],
        baseStats: expect.objectContaining({
          hp: 50,
          attack: 65,
          defense: 50,
          spAttack: 40,
          spDefense: 40,
          speed: 65,
        }),
      }),
    );
    expect(dm.getSpecies(SPECIES.dragapult)).toEqual(
      expect.objectContaining({
        id: 887,
        name: "dragapult",
        displayName: "Dragapult",
        types: [TYPES.dragon, TYPES.ghost],
        baseStats: expect.objectContaining({
          hp: 88,
          attack: 120,
          defense: 75,
          spAttack: 100,
          spDefense: 75,
          speed: 142,
        }),
      }),
    );
  });
});
