import { describe, expect, it } from "vitest";
import { createGen8DataManager } from "../src/data";

describe("Gen 8 DataManager -- data loading", () => {
  // ---------------------------------------------------------------------------
  // Pokemon
  // ---------------------------------------------------------------------------

  it("given gen8 data files, when loading DataManager, then loads at least 600 Pokemon", () => {
    // Source: Data generated by tools/data-importer/src/import-gen.ts --gen=8
    // Gen 8 (Sword/Shield) has a regional dex -- many older Pokemon are not
    // available. The importer pulls species #1-#905 but skips those not in
    // Showdown's Gen 8 data. Expect at least 600 species.
    const dm = createGen8DataManager();
    expect(dm.getAllSpecies().length).toBeGreaterThanOrEqual(600);
  });

  it("given gen8 data files, when loading DataManager, then loads exactly 664 Pokemon", () => {
    // Source: Data generated by tools/data-importer/src/import-gen.ts --gen=8
    // @pkmn/data Gen 8 iteration yields 664 base-form species (excludes
    // Pokemon cut from Sword/Shield's regional dex).
    const dm = createGen8DataManager();
    expect(dm.getAllSpecies().length).toBe(664);
  });

  it("given gen8 data files, when loading DataManager, then loads 646 moves", () => {
    // Source: @pkmn/data gen8 move count (646 moves available in Gen 8)
    const dm = createGen8DataManager();
    expect(dm.getAllMoves().length).toBe(646);
  });

  it("given gen8 data files, when loading DataManager, then loads 267 abilities", () => {
    // Source: @pkmn/data gen8 ability count (267 abilities through Gen 8)
    // Gen 8 added 34 new abilities (234-267) on top of Gen 7's 233.
    const dm = createGen8DataManager();
    expect(dm.getAllAbilities().length).toBe(267);
  });

  it("given gen8 data files, when loading DataManager, then loads 25 natures", () => {
    // Source: 25 natures introduced in Gen 3, unchanged through all generations
    const dm = createGen8DataManager();
    expect(dm.getAllNatures().length).toBe(25);
  });

  it("given gen8 data files, when loading DataManager, then loads 354 items", () => {
    // Source: @pkmn/data gen8 item count (354 items)
    const dm = createGen8DataManager();
    expect(dm.getAllItems().length).toBe(354);
  });

  // ---------------------------------------------------------------------------
  // Type chart
  // ---------------------------------------------------------------------------

  it("given gen8 type chart, when checking type count, then has exactly 18 types", () => {
    // Source: Gen 8 has 18 types (same as Gen 6-7, no new types added)
    // Source: Bulbapedia -- https://bulbapedia.bulbagarden.net/wiki/Generation_VIII
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(Object.keys(chart).length).toBe(18);
  });

  it("given gen8 type chart, when checking for Fairy, then Fairy exists", () => {
    // Source: Fairy type introduced in Gen 6, present in Gen 8
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart).toHaveProperty("fairy");
  });

  it("given gen8 type chart, when checking Fairy attacking Dragon, then Dragon is weak to Fairy (2x)", () => {
    // Source: Bulbapedia -- Fairy is super effective against Dragon
    // Source: references/pokemon-showdown/data/typechart.ts
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart.fairy?.dragon).toBe(2);
  });

  it("given gen8 type chart, when checking Dragon attacking Fairy, then Fairy is immune to Dragon (0x)", () => {
    // Source: Bulbapedia -- Fairy is immune to Dragon-type moves
    // Source: references/pokemon-showdown/data/typechart.ts
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart.dragon?.fairy).toBe(0);
  });

  it("given gen8 type chart, when checking Dark attacking Steel, then Steel is neutral to Dark (1x)", () => {
    // Source: references/pokemon-showdown/data/typechart.ts
    // In Gen 6+, Steel no longer resists Dark (was 0.5x in Gen 2-5)
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart.dark?.steel).toBe(1);
  });

  it("given gen8 type chart, when checking Ghost attacking Steel, then Steel is neutral to Ghost (1x)", () => {
    // Source: references/pokemon-showdown/data/typechart.ts
    // In Gen 6+, Steel no longer resists Ghost (was 0.5x in Gen 2-5)
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart.ghost?.steel).toBe(1);
  });

  it("given gen8 type chart, when checking Normal attacking Ghost, then Ghost is immune (0x)", () => {
    // Source: Bulbapedia -- Normal-type moves do not affect Ghost-type Pokemon
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart.normal?.ghost).toBe(0);
  });

  it("given gen8 type chart, when checking Steel attacking Fairy, then Fairy is weak to Steel (2x)", () => {
    // Source: Bulbapedia -- Steel is super effective against Fairy
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(chart.steel?.fairy).toBe(2);
  });

  // ---------------------------------------------------------------------------
  // Gen 8 Pokemon species
  // ---------------------------------------------------------------------------

  it("given gen8 data, when looking up Pikachu, then base stats match Bulbapedia", () => {
    // Source: Bulbapedia -- Pikachu (#25) base stats (unchanged since Gen 6):
    // HP=35, Atk=55, Def=40, SpA=50, SpD=50, Spe=90
    const dm = createGen8DataManager();
    const pikachu = dm.getSpeciesByName("pikachu");
    expect(pikachu.baseStats.hp).toBe(35);
    expect(pikachu.baseStats.attack).toBe(55);
    expect(pikachu.baseStats.defense).toBe(40);
    expect(pikachu.baseStats.spAttack).toBe(50);
    expect(pikachu.baseStats.spDefense).toBe(50);
    expect(pikachu.baseStats.speed).toBe(90);
  });

  it("given gen8 data, when looking up Grookey, then types are Grass", () => {
    // Source: Bulbapedia -- Grookey (#810) is a pure Grass-type
    // First starter of Gen 8 (Sword/Shield)
    const dm = createGen8DataManager();
    const grookey = dm.getSpeciesByName("grookey");
    expect(grookey.types).toEqual(["grass"]);
  });

  it("given gen8 data, when looking up Cinderace, then type is Fire", () => {
    // Source: Bulbapedia -- Cinderace (#815) is a pure Fire-type
    const dm = createGen8DataManager();
    const cinderace = dm.getSpeciesByName("cinderace");
    expect(cinderace.types).toEqual(["fire"]);
  });

  it("given gen8 data, when looking up Dragapult, then types are Dragon/Ghost", () => {
    // Source: Bulbapedia -- Dragapult (#887) is Dragon/Ghost
    const dm = createGen8DataManager();
    const dragapult = dm.getSpeciesByName("dragapult");
    expect(dragapult.types).toEqual(["dragon", "ghost"]);
  });

  it("given gen8 data, when looking up Dragapult, then base stats match Bulbapedia", () => {
    // Source: Bulbapedia -- Dragapult (#887) base stats:
    // HP=88, Atk=120, Def=75, SpA=100, SpD=75, Spe=142
    const dm = createGen8DataManager();
    const dragapult = dm.getSpeciesByName("dragapult");
    expect(dragapult.baseStats.hp).toBe(88);
    expect(dragapult.baseStats.attack).toBe(120);
    expect(dragapult.baseStats.defense).toBe(75);
    expect(dragapult.baseStats.spAttack).toBe(100);
    expect(dragapult.baseStats.spDefense).toBe(75);
    expect(dragapult.baseStats.speed).toBe(142);
  });

  it("given gen8 data, when looking up Zacian, then types are Fairy", () => {
    // Source: Bulbapedia -- Zacian (#888) base form is a pure Fairy-type
    // (Crowned form is Fairy/Steel, but base form is mono-Fairy)
    const dm = createGen8DataManager();
    const zacian = dm.getSpeciesByName("zacian");
    expect(zacian.types).toEqual(["fairy"]);
  });

  it("given gen8 data, when looking up Zamazenta, then types are Fighting", () => {
    // Source: Bulbapedia -- Zamazenta (#889) base form is a pure Fighting-type
    // (Crowned form is Fighting/Steel, but base form is mono-Fighting)
    const dm = createGen8DataManager();
    const zamazenta = dm.getSpeciesByName("zamazenta");
    expect(zamazenta.types).toEqual(["fighting"]);
  });

  it("given gen8 data, when looking up Eternatus, then types are Poison/Dragon", () => {
    // Source: Bulbapedia -- Eternatus (#890) is Poison/Dragon
    const dm = createGen8DataManager();
    const eternatus = dm.getSpeciesByName("eternatus");
    expect(eternatus.types).toEqual(["poison", "dragon"]);
  });

  // ---------------------------------------------------------------------------
  // Gen 8 moves
  // ---------------------------------------------------------------------------

  it("given gen8 moves, when looking up Behemoth Blade, then power is 100 and type is Steel", () => {
    // Source: Bulbapedia -- Behemoth Blade: Steel-type, 100 power, physical
    // Signature move of Zacian (Crowned Sword form)
    const dm = createGen8DataManager();
    const move = dm.getMove("behemoth-blade");
    expect(move.power).toBe(100);
    expect(move.type).toBe("steel");
    expect(move.category).toBe("physical");
  });

  it("given gen8 moves, when looking up Pyro Ball, then power is 120 and type is Fire", () => {
    // Source: Bulbapedia -- Pyro Ball: Fire-type, 120 power, physical
    // Signature move of Cinderace
    const dm = createGen8DataManager();
    const move = dm.getMove("pyro-ball");
    expect(move.power).toBe(120);
    expect(move.type).toBe("fire");
    expect(move.category).toBe("physical");
  });

  it("given gen8 moves, when looking up Grassy Glide, then power is 55 and type is Grass", () => {
    // Source: Bulbapedia -- Grassy Glide: Grass-type, 55 power (60 pre-nerf in Gen 9),
    // physical. Has increased priority in Grassy Terrain.
    // Note: In Gen 8 the base power was 70, but @pkmn/data may show the latest value.
    const dm = createGen8DataManager();
    const move = dm.getMove("grassy-glide");
    expect(move.type).toBe("grass");
    expect(move.category).toBe("physical");
    // Power may be 55 or 70 depending on data source generation
    expect(move.power).toBeGreaterThanOrEqual(55);
    expect(move.power).toBeLessThanOrEqual(70);
  });

  it("given gen8 moves, when looking up Wicked Blow, then power is 80 and type is Dark", () => {
    // Source: Bulbapedia -- Wicked Blow: Dark-type, 80 power, physical (buffed from 75 in Gen 9)
    // Signature move of Urshifu (Single Strike Style)
    // Always results in a critical hit
    const dm = createGen8DataManager();
    const move = dm.getMove("wicked-blow");
    expect(move.power).toBe(80);
    expect(move.type).toBe("dark");
    expect(move.category).toBe("physical");
  });

  // ---------------------------------------------------------------------------
  // Gen 8 abilities
  // ---------------------------------------------------------------------------

  it("given gen8 abilities, when looking up Libero, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Libero introduced in Gen 8 (Cinderace's hidden ability)
    // Changes the user's type to match the move being used before executing
    const dm = createGen8DataManager();
    const ability = dm.getAbility("libero");
    expect(ability.id).toBe("libero");
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Intrepid Sword, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Intrepid Sword introduced in Gen 8
    // Zacian's signature ability: raises Attack by one stage on switch-in
    const dm = createGen8DataManager();
    const ability = dm.getAbility("intrepid-sword");
    expect(ability.id).toBe("intrepid-sword");
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Dauntless Shield, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Dauntless Shield introduced in Gen 8
    // Zamazenta's signature ability: raises Defense by one stage on switch-in
    const dm = createGen8DataManager();
    const ability = dm.getAbility("dauntless-shield");
    expect(ability.id).toBe("dauntless-shield");
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Gorilla Tactics, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Gorilla Tactics introduced in Gen 8
    // Darmanitan-Galar's ability: boosts Attack by 1.5x but locks into one move
    const dm = createGen8DataManager();
    const ability = dm.getAbility("gorilla-tactics");
    expect(ability.id).toBe("gorilla-tactics");
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Neutralizing Gas, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Neutralizing Gas introduced in Gen 8
    // Weezing-Galar's ability: suppresses all other abilities while active
    const dm = createGen8DataManager();
    const ability = dm.getAbility("neutralizing-gas");
    expect(ability.id).toBe("neutralizing-gas");
    expect(ability.generation).toBe(8);
  });

  it("given gen8 abilities, when looking up Ice Scales, then it exists and is gen 8", () => {
    // Source: Bulbapedia -- Ice Scales introduced in Gen 8
    // Frosmoth's ability: halves damage from special moves
    const dm = createGen8DataManager();
    const ability = dm.getAbility("ice-scales");
    expect(ability.id).toBe("ice-scales");
    expect(ability.generation).toBe(8);
  });

  // ---------------------------------------------------------------------------
  // Gen 8 items
  // ---------------------------------------------------------------------------

  it("given gen8 items, when loading items, then Leftovers still exists", () => {
    // Source: Leftovers has existed since Gen 2, still present in Gen 8
    const dm = createGen8DataManager();
    const item = dm.getItem("leftovers");
    expect(item.id).toBe("leftovers");
  });

  it("given gen8 items, when loading items, then Choice Scarf exists", () => {
    // Source: Choice Scarf introduced in Gen 4, still present in Gen 8
    const dm = createGen8DataManager();
    const item = dm.getItem("choice-scarf");
    expect(item.id).toBe("choice-scarf");
  });

  it("given gen8 items, when loading items, then Heavy-Duty Boots exists", () => {
    // Source: Bulbapedia -- Heavy-Duty Boots introduced in Gen 8
    // Protects holder from entry hazards
    const dm = createGen8DataManager();
    const item = dm.getItem("heavy-duty-boots");
    expect(item.id).toBe("heavy-duty-boots");
  });

  it("given gen8 items, when loading items, then Utility Umbrella exists", () => {
    // Source: Bulbapedia -- Utility Umbrella introduced in Gen 8
    // The effects of weather are negated for the holder
    const dm = createGen8DataManager();
    const item = dm.getItem("utility-umbrella");
    expect(item.id).toBe("utility-umbrella");
  });

  // ---------------------------------------------------------------------------
  // Structural validation
  // ---------------------------------------------------------------------------

  it("given gen8 moves, when inspecting any move, then required fields are present", () => {
    // All moves must have id, type, category, pp, and priority
    const dm = createGen8DataManager();
    const moves = dm.getAllMoves();
    for (const move of moves) {
      expect(move.id).toBeTruthy();
      expect(move.type).toBeTruthy();
      expect(["physical", "special", "status"]).toContain(move.category);
      expect(move.pp).toBeGreaterThan(0);
      expect(typeof move.priority).toBe("number");
    }
  });

  it("given gen8 pokemon, when inspecting any species, then required fields are present", () => {
    // All species must have id, types, and baseStats with all 6 stats
    const dm = createGen8DataManager();
    const allSpecies = dm.getAllSpecies();
    for (const species of allSpecies) {
      expect(species.id).toBeTruthy();
      expect(species.types.length).toBeGreaterThanOrEqual(1);
      expect(species.types.length).toBeLessThanOrEqual(2);
      expect(species.baseStats.hp).toBeGreaterThan(0);
      expect(species.baseStats.attack).toBeGreaterThan(0);
      expect(species.baseStats.defense).toBeGreaterThan(0);
      expect(species.baseStats.spAttack).toBeGreaterThan(0);
      expect(species.baseStats.spDefense).toBeGreaterThan(0);
      expect(species.baseStats.speed).toBeGreaterThan(0);
    }
  });
});
