import { describe, expect, it } from "vitest";
import { createGen8DataManager } from "../src/data/index.js";

/**
 * Smoke tests for Gen 8 package.
 * Since Gen8Ruleset doesn't exist yet (Wave 1), these tests verify
 * that the data manager creates successfully and data loads correctly.
 */
describe("Gen8 data smoke test", () => {
  it("given gen8 data, when creating data manager, then it loads successfully", () => {
    // Source: Data generated by tools/data-importer/src/import-gen.ts --gen=8
    const dm = createGen8DataManager();
    expect(dm).toBeDefined();
  });

  it("given gen8 data manager, when querying species, then returns non-empty array", () => {
    // Source: Gen 8 has at least 600 species available
    const dm = createGen8DataManager();
    const species = dm.getAllSpecies();
    expect(species.length).toBeGreaterThan(0);
  });

  it("given gen8 data manager, when querying moves, then returns non-empty array", () => {
    // Source: Gen 8 has 646 moves
    const dm = createGen8DataManager();
    const moves = dm.getAllMoves();
    expect(moves.length).toBeGreaterThan(0);
  });

  it("given gen8 data manager, when querying type chart, then has 18 types", () => {
    // Source: Gen 8 uses 18-type chart (same as Gen 6-7)
    const dm = createGen8DataManager();
    const chart = dm.getTypeChart();
    expect(Object.keys(chart).length).toBe(18);
  });

  it("given gen8 data manager, when querying abilities, then returns non-empty array", () => {
    // Source: Gen 8 has 267 abilities
    const dm = createGen8DataManager();
    const abilities = dm.getAllAbilities();
    expect(abilities.length).toBeGreaterThan(0);
  });

  it("given gen8 data manager, when querying items, then returns non-empty array", () => {
    // Source: Gen 8 has 354 items
    const dm = createGen8DataManager();
    const items = dm.getAllItems();
    expect(items.length).toBeGreaterThan(0);
  });
});
