// @pokemon-lib-ts/gen8 -- Gen8Ruleset + complete Gen 8 data

export { createGen8DataManager } from "./data/index.js";
export {
  handleGen8ContactAbility,
  handleGen8FieldAbility,
  handleGen8SwitchInAbility,
} from "./Gen8Abilities.js";
export {
  getAteAbilityOverride,
  getDragonsMawMultiplier,
  getFurCoatMultiplier,
  getGorillaTacticsMultiplier,
  getIceScalesMultiplier,
  getMegaLauncherMultiplier,
  getMultiscaleMultiplier,
  getPunkRockIncomingMultiplier,
  getPunkRockMultiplier,
  getSheerForceMultiplier,
  getSteelworkerMultiplier,
  getStrongJawMultiplier,
  getSturdyDamageCap,
  getToughClawsMultiplier,
  getTransistorMultiplier,
  handleGen8DamageCalcAbility,
  handleGen8DamageImmunityAbility,
  hasSheerForceEligibleEffect,
  isParentalBondEligible,
  isSheerForceEligibleMove,
  PARENTAL_BOND_SECOND_HIT_MULTIPLIER,
  sheerForceSuppressesLifeOrb,
  sturdyBlocksOHKO,
} from "./Gen8AbilitiesDamage.js";
export {
  getTriagePriorityBonus,
  handleGen8StatAbility,
  isCottonDownTrigger,
  isDauntlessShieldTrigger,
  isGaleWingsActive,
  isIntrepidSwordTrigger,
  isPranksterBlockedByDarkType,
  isPranksterEligible,
  isQuickDrawTrigger,
  isSteamEngineTrigger,
} from "./Gen8AbilitiesStat.js";
export {
  getGulpMissileResult,
  getScreenCleanerTargets,
  getWeatherDuration,
  handleGen8SwitchAbility,
  hasMagicGuard,
  hasOvercoat,
  isBulletproofBlocked,
  isCramorantWithGulpMissile,
  isDampBlocked,
  isIceFaceActive,
  isLiberoActive,
  isMoldBreakerAbility,
  isNeutralizingGasActive,
  isNeutralizingGasImmune,
  isPastelVeilBlocking,
  isScreenCleaner,
  isSoundproofBlocked,
  MOLD_BREAKER_ALIASES,
  NEUTRALIZING_GAS_IMMUNE_ABILITIES,
  rollHarvest,
  rollShedSkin,
  SCREEN_CLEANER_SCREENS,
  shouldHungerSwitchToggle,
  shouldIceFaceReform,
  shouldMirrorArmorReflect,
  shouldPerishBodyTrigger,
  shouldWanderingSpiritSwap,
  TRACE_UNCOPYABLE_ABILITIES,
  UNSUPPRESSABLE_ABILITIES,
} from "./Gen8AbilitiesSwitch.js";
export { GEN8_CRIT_MULTIPLIER, GEN8_CRIT_RATE_TABLE } from "./Gen8CritCalc.js";
export {
  calculateGen8Damage,
  isGen8Grounded,
  pokeRound,
  TYPE_RESIST_BERRIES,
} from "./Gen8DamageCalc.js";
export { Gen8Ruleset } from "./Gen8Ruleset.js";
export {
  applyGen8TerrainEffects,
  checkGen8TerrainStatusImmunity,
  checkMistyTerrainConfusionImmunity,
  checkPsychicTerrainPriorityBlock,
  handleSurgeAbility,
  isSurgeAbility,
  TERRAIN_DEFAULT_TURNS,
  TERRAIN_EXTENDED_TURNS,
} from "./Gen8Terrain.js";
export { GEN8_TYPE_CHART, GEN8_TYPES } from "./Gen8TypeChart.js";
