// @pokemon-lib-ts/gen8 -- Gen8Ruleset + complete Gen 8 data

export { createGen8DataManager } from "./data/index.js";
export {
  getAteAbilityOverride,
  getDragonsMawMultiplier,
  getFurCoatMultiplier,
  getGorillaTacticsMultiplier,
  getIceScalesMultiplier,
  getMegaLauncherMultiplier,
  getMultiscaleMultiplier,
  getPunkRockIncomingMultiplier,
  getPunkRockMultiplier,
  getSheerForceMultiplier,
  getSteelworkerMultiplier,
  getStrongJawMultiplier,
  getSturdyDamageCap,
  getToughClawsMultiplier,
  getTransistorMultiplier,
  handleGen8DamageCalcAbility,
  handleGen8DamageImmunityAbility,
  hasSheerForceEligibleEffect,
  isParentalBondEligible,
  isSheerForceEligibleMove,
  PARENTAL_BOND_SECOND_HIT_MULTIPLIER,
  sheerForceSuppressesLifeOrb,
  sturdyBlocksOHKO,
} from "./Gen8AbilitiesDamage.js";
export {
  getTriagePriorityBonus,
  handleGen8StatAbility,
  isCottonDownTrigger,
  isDauntlessShieldTrigger,
  isGaleWingsActive,
  isIntrepidSwordTrigger,
  isPranksterBlockedByDarkType,
  isPranksterEligible,
  isQuickDrawTrigger,
  isSteamEngineTrigger,
} from "./Gen8AbilitiesStat.js";
export { GEN8_CRIT_MULTIPLIER, GEN8_CRIT_RATE_TABLE } from "./Gen8CritCalc.js";
export {
  calculateGen8Damage,
  isGen8Grounded,
  pokeRound,
  TYPE_RESIST_BERRIES,
} from "./Gen8DamageCalc.js";
export {
  AURORA_VEIL_DEFAULT_TURNS,
  AURORA_VEIL_LIGHT_CLAY_TURNS,
  calculateClangorousSoulCost,
  calculateObstructPenalty,
  calculateSpikyShieldDamage,
  calculateSteelBeamRecoil,
  executeGen8Defog,
  executeGen8MoveEffect,
  getFishiousBoltBeakPower,
  getRapidSpinSpeedBoost,
  handleDrainEffect,
  handleJawLock,
  handleNoRetreat,
  handleTarShot,
  isAntiDynamaxMove,
  isBlockedByBanefulBunker,
  isBlockedByCraftyShield,
  isBlockedByKingsShield,
  isBlockedByMatBlock,
  isBlockedByObstruct,
  isBlockedBySpikyShield,
  isBodyPress,
  isGen8GrassPowderBlocked,
  isSteelBeamRecoil,
  isTarShotActive,
} from "./Gen8MoveEffects.js";
export { Gen8Ruleset } from "./Gen8Ruleset.js";
export {
  applyGen8TerrainEffects,
  checkGen8TerrainStatusImmunity,
  checkMistyTerrainConfusionImmunity,
  checkPsychicTerrainPriorityBlock,
  handleSurgeAbility,
  isSurgeAbility,
  TERRAIN_DEFAULT_TURNS,
  TERRAIN_EXTENDED_TURNS,
} from "./Gen8Terrain.js";
export { GEN8_TYPE_CHART, GEN8_TYPES } from "./Gen8TypeChart.js";
