// @pokemon-lib-ts/gen8/internal -- broader helper/testing surface

export * from "./data/index.js";
export {
  handleGen8ContactAbility,
  handleGen8FieldAbility,
  handleGen8SwitchInAbility,
} from "./Gen8Abilities.js";
export {
  getAteAbilityOverride,
  getDragonsMawMultiplier,
  getFurCoatMultiplier,
  getGorillaTacticsMultiplier,
  getIceScalesMultiplier,
  getMegaLauncherMultiplier,
  getMultiscaleMultiplier,
  getPunkRockIncomingMultiplier,
  getPunkRockMultiplier,
  getSheerForceMultiplier,
  getSteelworkerMultiplier,
  getStrongJawMultiplier,
  getSturdyDamageCap,
  getToughClawsMultiplier,
  getTransistorMultiplier,
  handleGen8DamageCalcAbility,
  handleGen8DamageImmunityAbility,
  hasSheerForceEligibleEffect,
  isParentalBondEligible,
  isSheerForceEligibleMove,
  PARENTAL_BOND_SECOND_HIT_MULTIPLIER,
  sheerForceSuppressesLifeOrb,
  sturdyBlocksOHKO,
} from "./Gen8AbilitiesDamage.js";
export {
  getTriagePriorityBonus,
  handleGen8StatAbility,
  isCottonDownTrigger,
  isDauntlessShieldTrigger,
  isGaleWingsActive,
  isIntrepidSwordTrigger,
  isPranksterBlockedByDarkType,
  isPranksterEligible,
  isQuickDrawTrigger,
  isSteamEngineTrigger,
} from "./Gen8AbilitiesStat.js";
export {
  getGulpMissileResult,
  getScreenCleanerTargets,
  getWeatherDuration,
  handleGen8SwitchAbility,
  hasMagicGuard,
  hasOvercoat,
  isBulletproofBlocked,
  isCramorantWithGulpMissile,
  isDampBlocked,
  isIceFaceActive,
  isLiberoActive,
  isMoldBreakerAbility,
  isNeutralizingGasActive,
  isNeutralizingGasImmune,
  isPastelVeilBlocking,
  isScreenCleaner,
  isSoundproofBlocked,
  MOLD_BREAKER_ALIASES,
  NEUTRALIZING_GAS_IMMUNE_ABILITIES,
  rollHarvest,
  rollShedSkin,
  SCREEN_CLEANER_SCREENS,
  shouldHungerSwitchToggle,
  shouldIceFaceReform,
  shouldMirrorArmorReflect,
  shouldPerishBodyTrigger,
  shouldWanderingSpiritSwap,
  TRACE_UNCOPYABLE_ABILITIES,
  UNSUPPRESSABLE_ABILITIES,
} from "./Gen8AbilitiesSwitch.js";
export {
  GEN8_CRIT_MULTIPLIER,
  GEN8_CRIT_RATE_PROBABILITIES,
  GEN8_CRIT_RATE_TABLE,
} from "./Gen8CritCalc.js";
export {
  calculateGen8Damage,
  isGen8Grounded,
  pokeRound,
  TYPE_RESIST_BERRIES,
} from "./Gen8DamageCalc.js";
export {
  DYNAMAX_IMMUNE_SPECIES,
  DYNAMAX_TURNS,
  Gen8Dynamax,
  getDynamaxCurrentHp,
  getDynamaxMaxHp,
  getUndynamaxedHp,
} from "./Gen8Dynamax.js";
export {
  applyGen8EntryHazards,
  applyGen8GMaxSteelsurge,
  applyGen8SpikesHazard,
  applyGen8StealthRock,
  applyGen8StickyWeb,
  applyGen8ToxicSpikes,
  hasHeavyDutyBoots,
} from "./Gen8EntryHazards.js";
export {
  GMAX_MOVES,
  type GMaxMoveData,
  type GMaxMoveEffectType,
  getGMaxMove,
  getGMaxMoveEffect,
  isGigantamaxEligible,
} from "./Gen8GMaxMoves.js";
export {
  applyGen8HeldItem,
  getBlackSludgeEffect,
  getBlunderPolicyTrigger,
  getChoiceItemBoost,
  getConsumableItemEffect,
  getEjectPackTrigger,
  getEvioliteModifier,
  getFocusSashTrigger,
  getItemDamageModifier,
  getLeftoversHeal,
  getLifeOrbRecoil,
  getPinchBerryThreshold,
  getRockyHelmetDamage,
  getRoomServiceTrigger,
  getThroatSprayTrigger,
  getTypeBoostItem,
  getTypeResistBerry,
  hasAirBalloon,
  hasIronBall,
  hasUtilityUmbrella,
  isAssaultVestHolder,
  isChoiceLocked,
  isGen8PowderBlocked,
} from "./Gen8Items.js";
export {
  getMaxMoveName,
  getMaxMovePower,
  getMaxMoveSecondaryEffect,
  isMaxGuard,
  type MaxMoveEffect,
} from "./Gen8MaxMoves.js";
export {
  AURORA_VEIL_DEFAULT_TURNS,
  AURORA_VEIL_LIGHT_CLAY_TURNS,
  calculateClangorousSoulCost,
  calculateObstructPenalty,
  calculateSpikyShieldDamage,
  calculateSteelBeamRecoil,
  executeGen8Defog,
  executeGen8MoveEffect,
  getFishiousBoltBeakPower,
  getRapidSpinSpeedBoost,
  handleDrainEffect,
  handleJawLock,
  handleNoRetreat,
  handleTarShot,
  isAntiDynamaxMove,
  isBlockedByBanefulBunker,
  isBlockedByCraftyShield,
  isBlockedByKingsShield,
  isBlockedByMatBlock,
  isBlockedByObstruct,
  isBlockedBySpikyShield,
  isBodyPress,
  isGen8GrassPowderBlocked,
  isSteelBeamRecoil,
  isTarShotActive,
} from "./Gen8MoveEffects.js";
export { Gen8Ruleset } from "./Gen8Ruleset.js";
export {
  applyGen8TerrainEffects,
  checkGen8TerrainStatusImmunity,
  checkMistyTerrainConfusionImmunity,
  checkPsychicTerrainPriorityBlock,
  handleSurgeAbility,
  isSurgeAbility,
  TERRAIN_DEFAULT_TURNS,
  TERRAIN_EXTENDED_TURNS,
} from "./Gen8Terrain.js";
export {
  ABILITY_WEATHER_TURNS,
  applyGen8WeatherEffects,
  HAIL_IMMUNE_TYPES,
  isGen8WeatherImmune,
  isWeatherSuppressedGen8,
  isWeatherSuppressedOnFieldGen8,
  SANDSTORM_IMMUNE_TYPES,
  WEATHER_ROCK_EXTENSION,
} from "./Gen8Weather.js";
